# import os
# mapNames = os.listdir("F:\games\StarCraft II\Maps")
# for map in mapNames:
#     print('"', map, '",')

mapNames = [
    "(2)16-BitLE",
    "(2)AcidPlantLE",
    "(2)Bel'ShirVestigeLE (Void)",
    "(2)CatalystLE",
    "(2)DreamcatcherLE",
    "(2)LostandFoundLE",
    "(2)RedshiftLE",
    "(4)DarknessSanctuaryLE",
    "2000AtmospheresAIE",
    "AbiogenesisLE",
    "AbyssalReefLE",
    "AcidPlantLE",
    "AcolyteLE",
    "AcropolisLE",
    "AscensiontoAiurLE",
    "AutomatonLE",
    "BackwaterLE",
    "BattleontheBoardwalkLE",
    "BelShirVestigeLE",
    "BerlingradAIE",
    "BlackburnAIE",
    "BlackpinkLE",
    "BloodBoilLE",
    "BlueshiftLE",
    "CactusValleyLE",
    "CatalystLE",
    "CeruleanFallLE",
    "CuriousMindsAIE",
    "CyberForestLE",
    "DefendersLandingLE",
    "DiscoBloodbathLE",
    "DreamcatcherLE",
    "EastwatchLE",
    "Empty128",
    "EphemeronLE",
    "Flat128",
    "Flat32",
    "Flat48",
    "Flat482Spawns",
    "Flat64",
    "Flat96",
    "FractureLE",
    "FrostLE",
    "GlitteringAshesAIE",
    "HardwireAIE",
    "HonorgroundsLE",
    "InterloperLE",
    "KairosJunctionLE",
    "KingsCoveLE",
    "LostandFoundLE",
    "MechDepotLE",
    "NeonVioletSquareLE",
    "NewkirkPrecinctTE",
    "NewRepugnancyLE",
    "OdysseyLE",
    "PaladinoTerminalLE",
    "ParaSiteLE",
    "PortAleksanderLE",
    "ProximaStationLE",
    "SequencerLE",
    "Simple128",
    "Simple64",
    "Simple96",
    "StasisLE",
    "ThunderbirdLE",
    "TritonLE",
    "TurboCruise'84LE",
    "WintersGateLE",
    "WorldofSleepersLE",
    "YearZeroLE",
]
